
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'guide-delivery-agent',
      '--source=.', '--region=europe-west1',
      '--platform=managed', '--allow-unauthenticated',
      '--set-env-vars', 'Z_API_KEY=your-zoho-token,SMTP_USER=robertf@fourgears.com,SMTP_PASS=your-smtp-password',
      '--runtime=nodejs18', '--entry-point=index.js'
    ]
